### PR TITLE
build: Assembles for last IntelliJ version

### LINKED ISSUE #3: PhpStorm 223.* compatibility
Plugin currently not compatible with PhpStorm 2022.3 RC (223.*)

image
image

### PR DESCRIPTION
**Pull request by githubjeka**
Successful installation on IntelliJ 223 branch number

image

Closes https://github.com/VKCOM/modulite/issues/3

### CODE REVIEW

**Review by Danil42Russia — APPROVED** [review]
Thanks!

**Comment by githubjeka** [comment]
The installation completed successfully, but some things do not work as requested in manual. But these are others issues.

**Comment by Danil42Russia** [comment]
> The installation completed successfully, but some things do not work as requested in manual. But these are others issues.

Can you tell me what's not working right? 😰

**Comment by githubjeka** [comment]
Working only this 
image

Cant create `@internal` class. Only test command available.
image

Havent restricted error.
image
image
image

**Comment by Danil42Russia** [comment]
@githubjeka, I checked on 2022.3 and it works for me.

Снимок экрана 2022-12-13 в 23 25 53

Снимок экрана 2022-12-13 в 23 25 29

Снимок экрана 2022-12-13 в 23 29 56

Снимок экрана 2022-12-13 в 23 30 10

**Comment by githubjeka** [comment]
I reset IDE to default setting. Reinstall this plugin. Did not help.
Can you show your `compose.json`?

```json
{
  "autoload": {
    "psr-4": {
      "ModuleA\\": "src/ModuleA/",
      "ModuleB\\": "src/ModuleB/"
    }
  }
}
```

and it's normal or something is missing on my computer  ?

image

**Comment by Danil42Russia** [comment]
@githubjeka, please create a new issue so that we can discuss the problem with you. :)

**Pull request merged**
